server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: taskflow_user
    password: taskflow_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"

jwt:
  secret: dev-secret-should-be-at-least-32-characters
  expiration: 86400000

logging:
  level:
    com.taskflow.api: DEBUG
    org.springframework.security: DEBUG
