# Production Configuration

server:
  port: ${PORT:8080}

# Database Configuration
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/taskflow}
    username: ${DATABASE_USERNAME:taskflow_user}
    password: ${DATABASE_PASSWORD:taskflow_password}
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # CORS Configuration
  web:
    cors:
      allowed-origins: ${CORS_ORIGINS:*}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}

# Logging Configuration
logging:
  level:
    com.taskflow.api: INFO
    org.springframework.security: WARN
